nome = str(input("Digite seu nome completo: ")).strip()
print(f"Muito prazer em te conhecer {nome}!")
print(f"Seu primeiro nome é {nome.split()[0]}")
print(f"Seu último nome é {nome.split()[-1]}")
print(f'Seu nome tem ao todo {len(nome) - nome.count(" ")} letras')
print(f"Seu nome tem ao todo {len(nome.split()[0])} letras no primeiro nome")
print(f"Seu nome tem ao todo {len(nome.split()[-1])} letras no último nome")
print(f'Seu nome invertido é {" ".join(nome.split()[::-1])}')
print(f"Seu nome em minúsculas é {nome.lower()}")
print(f"Seu nome em maiúsculas é {nome.upper()}")
print(f'Seu nome tem ao todo {nome.count("A")} letras A')
print(f'A primeira letra "A" aparece na posição {nome.find("A") + 1}')
print(f'A última letra "A" aparece na posição {nome.rfind("A") + 1}')
print(f"Seu nome sem espaços extras é {nome.strip()}")
